version: "3.3"

volumes:
  pgdata:


services:
  db:
    image: postgres:14
    container_name: radioapp_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
